import { Artifact } from '../types';

export const mockArtifacts: Artifact[] = [
  {
    id: '1',
    name: 'Ancient Egyptian Vase',
    description:
      'A beautifully crafted ceramic vase from the New Kingdom period, featuring hieroglyphic inscriptions and intricate patterns depicting daily life in ancient Egypt.',
    historicalPeriod: 'New Kingdom (1550-1077 BCE)',
    imageUrl: 'https://example.com/images/egyptian-vase.jpg',
    model3DUrl: 'https://example.com/models/egyptian-vase.glb',
    rating: 4.8,
    isActive: true,
    museumId: 'museum-1',
    createdBy: 'curator-1',
    metadata: {
      type: 'Ceramic',
      material: 'Clay with gold inlay',
      discoveryLocation: 'Valley of the Kings, Egypt',
    },
    createdAt: '2024-01-15T10:30:00Z',
    updatedAt: '2024-01-20T14:45:00Z',
  },
  {
    id: '2',
    name: 'Roman Gladius Sword',
    description:
      'A well-preserved gladius sword used by Roman legionnaires, showcasing the superior metalworking skills of ancient Roman smiths.',
    historicalPeriod: 'Roman Empire (27 BCE - 476 CE)',
    imageUrl: 'https://example.com/images/roman-gladius.jpg',
    model3DUrl: 'https://example.com/models/roman-gladius.glb',
    rating: 4.6,
    isActive: true,
    museumId: 'museum-1',
    createdBy: 'curator-2',
    metadata: {
      type: 'Weapon',
      material: 'Iron and bronze',
      discoveryLocation: 'Pompeii, Italy',
    },
    createdAt: '2024-01-10T08:15:00Z',
    updatedAt: '2024-01-25T16:20:00Z',
  },
  {
    id: '3',
    name: 'Ming Dynasty Porcelain Bowl',
    description:
      'An exquisite blue and white porcelain bowl from the Ming Dynasty, featuring traditional Chinese motifs and exceptional craftsmanship.',
    historicalPeriod: 'Ming Dynasty (1368-1644)',
    imageUrl: 'https://example.com/images/ming-bowl.jpg',
    model3DUrl: 'https://example.com/models/ming-bowl.glb',
    rating: 4.9,
    isActive: true,
    museumId: 'museum-1',
    createdBy: 'curator-1',
    metadata: {
      type: 'Porcelain',
      material: 'Fine porcelain with cobalt blue glaze',
      discoveryLocation: 'Jingdezhen, China',
    },
    createdAt: '2024-01-05T12:00:00Z',
    updatedAt: '2024-01-18T09:30:00Z',
  },
  {
    id: '4',
    name: 'Mayan Jade Mask',
    description:
      'A ceremonial jade mask believed to have been worn by Mayan nobility during religious ceremonies, carved with intricate detail.',
    historicalPeriod: 'Classic Maya (250-900 CE)',
    imageUrl: 'https://example.com/images/mayan-mask.jpg',
    model3DUrl: 'https://example.com/models/mayan-mask.glb',
    rating: 4.7,
    isActive: false,
    museumId: 'museum-1',
    createdBy: 'curator-3',
    metadata: {
      type: 'Ceremonial',
      material: 'Jade with obsidian inlay',
      discoveryLocation: 'Tikal, Guatemala',
    },
    createdAt: '2024-01-08T15:45:00Z',
    updatedAt: '2024-01-22T11:10:00Z',
  },
  {
    id: '5',
    name: 'Viking Silver Bracelet',
    description:
      'A twisted silver bracelet with runic inscriptions, typical of Viking Age jewelry and craftsmanship from Scandinavia.',
    historicalPeriod: 'Viking Age (793-1066 CE)',
    imageUrl: 'https://example.com/images/viking-bracelet.jpg',
    model3DUrl: 'https://example.com/models/viking-bracelet.glb',
    rating: 4.4,
    isActive: true,
    museumId: 'museum-1',
    createdBy: 'curator-2',
    metadata: {
      type: 'Jewelry',
      material: 'Silver with runic engravings',
      discoveryLocation: 'Bergen, Norway',
    },
    createdAt: '2024-01-12T09:20:00Z',
    updatedAt: '2024-01-28T13:55:00Z',
  },
  {
    id: '6',
    name: 'Greek Amphora',
    description:
      'A large ceramic amphora used for storing wine and oil, decorated with scenes from Greek mythology and daily life.',
    historicalPeriod: 'Classical Greece (480-323 BCE)',
    imageUrl: 'https://example.com/images/greek-amphora.jpg',
    model3DUrl: 'https://example.com/models/greek-amphora.glb',
    rating: 4.5,
    isActive: true,
    museumId: 'museum-1',
    createdBy: 'curator-1',
    metadata: {
      type: 'Storage Vessel',
      material: 'Terracotta with black-figure painting',
      discoveryLocation: 'Athens, Greece',
    },
    createdAt: '2024-01-03T14:30:00Z',
    updatedAt: '2024-01-19T10:15:00Z',
  },
  {
    id: '7',
    name: 'Aztec Obsidian Knife',
    description:
      'A ritual obsidian knife with intricate handle carving, used in Aztec ceremonies and demonstrating their advanced knapping techniques.',
    historicalPeriod: 'Aztec Empire (1428-1521)',
    imageUrl: 'https://example.com/images/aztec-knife.jpg',
    model3DUrl: 'https://example.com/models/aztec-knife.glb',
    rating: 4.3,
    isActive: true,
    museumId: 'museum-1',
    createdBy: 'curator-3',
    metadata: {
      type: 'Ritual Tool',
      material: 'Obsidian with wooden handle',
      discoveryLocation: 'Tenochtitlan, Mexico',
    },
    createdAt: '2024-01-07T11:45:00Z',
    updatedAt: '2024-01-24T15:30:00Z',
  },
  {
    id: '8',
    name: 'Medieval Illuminated Manuscript',
    description:
      'A beautifully illuminated manuscript page featuring gold leaf and vibrant pigments, showcasing medieval European artistry.',
    historicalPeriod: 'Medieval Period (1000-1300 CE)',
    imageUrl: 'https://example.com/images/medieval-manuscript.jpg',
    model3DUrl: 'https://example.com/models/medieval-manuscript.glb',
    rating: 4.8,
    isActive: false,
    museumId: 'museum-1',
    createdBy: 'curator-2',
    metadata: {
      type: 'Manuscript',
      material: 'Parchment with gold leaf and mineral pigments',
      discoveryLocation: 'Canterbury, England',
    },
    createdAt: '2024-01-02T16:00:00Z',
    updatedAt: '2024-01-21T12:40:00Z',
  },
  {
    id: '9',
    name: 'Japanese Samurai Katana',
    description:
      'An authentic katana sword from the Edo period, featuring a beautifully forged blade and traditional tsuba (hand guard).',
    historicalPeriod: 'Edo Period (1603-1868)',
    imageUrl: 'https://example.com/images/samurai-katana.jpg',
    model3DUrl: 'https://example.com/models/samurai-katana.glb',
    rating: 4.9,
    isActive: true,
    museumId: 'museum-1',
    createdBy: 'curator-1',
    metadata: {
      type: 'Weapon',
      material: 'Folded steel with silk-wrapped handle',
      discoveryLocation: 'Kyoto, Japan',
    },
    createdAt: '2024-01-14T13:20:00Z',
    updatedAt: '2024-01-27T08:50:00Z',
  },
  {
    id: '10',
    name: 'Native American Dreamcatcher',
    description:
      'A traditional dreamcatcher with intricate beadwork and feathers, representing the spiritual beliefs of Plains Native Americans.',
    historicalPeriod: 'Pre-Columbian (1200-1500 CE)',
    imageUrl: 'https://example.com/images/dreamcatcher.jpg',
    model3DUrl: 'https://example.com/models/dreamcatcher.glb',
    rating: 4.2,
    isActive: true,
    museumId: 'museum-1',
    createdBy: 'curator-3',
    metadata: {
      type: 'Spiritual',
      material: 'Willow wood, sinew, feathers, and beads',
      discoveryLocation: 'Great Plains, USA',
    },
    createdAt: '2024-01-09T17:10:00Z',
    updatedAt: '2024-01-26T14:25:00Z',
  },
  {
    id: '11',
    name: 'Persian Carpet Fragment',
    description:
      'A fragment of a Persian carpet from the Safavid period, showing the incredible detail and artistry of Persian weavers.',
    historicalPeriod: 'Safavid Dynasty (1501-1736)',
    imageUrl: 'https://example.com/images/persian-carpet.jpg',
    model3DUrl: 'https://example.com/models/persian-carpet.glb',
    rating: 4.6,
    isActive: true,
    museumId: 'museum-1',
    createdBy: 'curator-2',
    metadata: {
      type: 'Textile',
      material: 'Silk and wool with natural dyes',
      discoveryLocation: 'Isfahan, Iran',
    },
    createdAt: '2024-01-11T10:35:00Z',
    updatedAt: '2024-01-23T16:45:00Z',
  },
  {
    id: '12',
    name: 'Celtic Bronze Torque',
    description:
      'A twisted bronze neck torque worn by Celtic nobility, demonstrating the sophisticated metalworking skills of ancient Celtic artisans.',
    historicalPeriod: 'Iron Age Celtic (800-100 BCE)',
    imageUrl: 'https://example.com/images/celtic-torque.jpg',
    model3DUrl: 'https://example.com/models/celtic-torque.glb',
    rating: 4.4,
    isActive: false,
    museumId: 'museum-1',
    createdBy: 'curator-1',
    metadata: {
      type: 'Jewelry',
      material: 'Bronze with intricate twisted design',
      discoveryLocation: 'Hallstatt, Austria',
    },
    createdAt: '2024-01-06T12:50:00Z',
    updatedAt: '2024-01-29T11:20:00Z',
  },
];

export const mockArtifactsPaginated = {
  data: mockArtifacts,
  pagination: {
    page: 1,
    pageSize: 10,
    totalItems: 12,
    totalPages: 2,
  },
};
